
/*
Campo id queda como AutoIncrement
*/

ALTER TABLE `tb_usuario` CHANGE `ID_USUARIO` `ID_USUARIO` INT(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `tb_usuario` CHANGE `TELEFONO` `TELEFONO` VARCHAR(11) NULL DEFAULT NULL;

ALTER TABLE `tb_usuario` CHANGE `CELULAR` `CELULAR` VARCHAR(11) NULL DEFAULT NULL;

     
ALTER TABLE `idea_log` CHANGE `FECHA` `FECHA` DATETIME NULL DEFAULT NULL;

ALTER TABLE `ideasplus`.`idea_log`
  ADD COLUMN `USUARIO` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
  
CREATE TRIGGER idea_log
BEFORE INSERT ON tb_idea
FOR EACH ROW
BEGIN
  INSERT INTO idea_log (USUARIO, FECHA)
      values (CURRENT_USER(), NOW());
END;