
/*
Campo id queda como AutoIncrement
*/

ALTER TABLE `tb_usuario` CHANGE `ID_USUARIO` `ID_USUARIO` INT(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `tb_usuario` CHANGE `TELEFONO` `TELEFONO` VARCHAR(11) NULL DEFAULT NULL;

ALTER TABLE `tb_usuario` CHANGE `CELULAR` `CELULAR` VARCHAR(11) NULL DEFAULT NULL;

     
ALTER TABLE `idea_log` CHANGE `FECHA` `FECHA` DATETIME NULL DEFAULT NULL;

ALTER TABLE `ideasplus`.`idea_log`
  ADD COLUMN `USUARIO` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
  
CREATE TRIGGER idea_log
BEFORE INSERT ON tb_idea
FOR EACH ROW
BEGIN
  INSERT INTO idea_log (USUARIO, FECHA)
      values (CURRENT_USER(), NOW());
END;

/*
Cambios hechos l 28 de ayo a las 10:38 pm
*/

ALTER TABLE `ideasplus`.`idea_log`
  DROP INDEX `ID_IDEA`;
  
ALTER TABLE `ideasplus`.`idea_log`
  CHANGE COLUMN `PRIVADA` `PRIVADO` tinyint(1) NULL DEFAULT NULL;


DROP TRIGGER idea_log;
CREATE TRIGGER idea_Trigger
AFTER UPDATE ON tb_idea FOR EACH ROW
BEGIN
INSERT INTO idea_log (USUARIO, FECHA, ID_IDEA, TITULO, DESCRIPCIO, PRIVADO, AREA, USUARIO_CREA, ESTUDIANTE, DOCENTE, ESTADO)
VALUES (user(), now(), OLD.ID_IDEA, OLD.TITULO, OLD.DESCRIPCION, OLD.PRIVADO, OLD.ID_AREA, OLD.ID_USUARIO_CREA, OLD.ID_ESTUDIANTE, OLD.ID_DOCENTE, OLD.ID_ESTADO);
END;

  
  
